### ISSUE TITLE
WPML and Subdirectories

### ISSUE THREAD

**Issue by fabianhenzler** [Objectivco/WordPressMultisiteSubdirectoryValetDriver#1]
Hi,

first of all - thanks for the efforts!
Is it working with WPML and Subdirectories like //domain.dev/en/wp-admin?

I'm getting a 404 with your Driver active. Any hints? 
Is it even necessary anymore with Valet ^2 because of nginx?

**Comment by clifgriffin** [comment]
@fabianhenzler We're on Valet 2.x as well. 

I don't have any great ideas on what could cause that, but I'd recommend debugging by editing the driver. You can `var_dump` and `die` and anything else. 

First thing I'd test is that line 15 is returning true. If it's not, the rest of the routing logic won't be invoked. 

https://github.com/Objectivco/WordPressMultisiteSubdirectoryValetDriver/blob/master/WordPressMultisiteSubdirectoryValetDriver.php#L15
