### ISSUE TITLE
Site spesific cron jobs

### ISSUE THREAD

**Issue by leaase** [Objectivco/WordPressMultisiteSubdirectoryValetDriver#2]
Hi :)
As I mentioned in this issue (https://github.com/laravel/valet/issues/360) on Laravel Valet repository, I'm having problems with site spesific cron jobs.

When I call https://domain.dev/sitename/wp-cron.php I get a 404 response. The call to https://domain.dev/wp-cron.php works, but then the site spesific cron jobs don't get executed.

So what I think need to happen is that a call to https://domain.dev/sitename/wp-cron.php should trigger https://domain.dev/wp-cron.php but with the 'sitename' as current site instead of the default blog.

I'm not sure how to do that, but will post here if I stumble upon a solution.

**Comment by clifgriffin** [comment]
Hi @leaase.

Can you try adding this to line 37?

```
        if ( stripos($uri, 'wp-cron.php') !== false ) {
            $new_uri = substr($uri, stripos($uri, '/wp-') );  
                      
            if ( file_exists( $sitePath . $new_uri ) ) {
                return $sitePath . $new_uri;
            }
        }
```

**Comment by leaase** [comment]
Yes :) That worked! Thanks 👍

**Comment by clifgriffin** [comment]
Great, I've pushed up a new version.
