### ISSUE TITLE
Issues with Wordpress files in wp folder

### ISSUE THREAD

**Issue by jeremybasolo** [Objectivco/WordPressMultisiteSubdirectoryValetDriver#3]
Hi,

Thanks for your work! 
I have an issue accessing the administration area and I think it's related to the way my WP installation is setup. I have a content folder to replace the wp-content folder and the wordpress files are located in a wp folder. I have the below constant variables defined in my wp-config.php:

if (!defined('WP_HOME')) {
    define('WP_HOME', 'http://whatever.dev');
}
if (!defined('WP_SITEURL')) {
    define('WP_SITEURL', WP_HOME .'/wp');
}
if (!defined('WP_CONTENT_DIR')) {
    define('WP_CONTENT_DIR', dirname(__FILE__) . '/content');
}
if (!defined('WP_CONTENT_URL')) {
    define('WP_CONTENT_URL', WP_HOME.'/content');
}

When I try to access /wp-admin/ or /wp/wp-admin/, it just redirects to /. I tried to var_dump through your driver php file but I haven't got a clue why this is happening... The redirection doesn't even seem to come from that file, more from the wp install I reckon.

Any idea?
Thanks

**Comment by clifgriffin** [comment]
So, I found this issue while trying to tackle this problem for myself. 

I'll let you know what I find...these custom drivers are definitely super confusing!

**Comment by clifgriffin** [comment]
This is fixed in the latest commit. Enjoy!

**Comment by clifgriffin** [comment]
Commit: https://github.com/Objectivco/WordPressMultisiteSubdirectoryValetDriver/commit/675211943018638e760e5b59fdb23aaf1583b5ca
